name: Update Forked Repo

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get GITHUB_TOKEN from secrets
        run: export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Update Fork
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/roborregosteam/RoBorregos/merge-upstream \
          -d '{"branch":"main"}'
